[2023-12-12T23:14:38.428+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_exchange_v02.load_to_postgres scheduled__2023-12-03T10:00:00+00:00 [queued]>
[2023-12-12T23:14:38.512+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_exchange_v02.load_to_postgres scheduled__2023-12-03T10:00:00+00:00 [queued]>
[2023-12-12T23:14:38.588+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-12-12T23:14:38.729+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2023-12-03 10:00:00+00:00
[2023-12-12T23:14:38.882+0000] {standard_task_runner.py:57} INFO - Started process 22990 to run task
[2023-12-12T23:14:38.998+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'currency_exchange_v02', 'load_to_postgres', 'scheduled__2023-12-03T10:00:00+00:00', '--job-id', '411', '--raw', '--subdir', 'DAGS_FOLDER/currency_exchange_dag.py', '--cfg-path', '/tmp/tmp5h851e4g']
[2023-12-12T23:14:39.185+0000] {standard_task_runner.py:85} INFO - Job 411: Subtask load_to_postgres
[2023-12-12T23:14:39.811+0000] {task_command.py:416} INFO - Running <TaskInstance: currency_exchange_v02.load_to_postgres scheduled__2023-12-03T10:00:00+00:00 [running]> on host d5f251ea7e03
[2023-12-12T23:14:41.097+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='currency' AIRFLOW_CTX_DAG_ID='currency_exchange_v02' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-03T10:00:00+00:00'
[2023-12-12T23:14:42.037+0000] {base.py:73} INFO - Using connection ID 'currency' for task execution.
[2023-12-12T23:14:42.595+0000] {sql.py:418} INFO - Running statement: 
        INSERT INTO usd_exchange_rate(dt, euro, yen, inr)
        VALUES (%s, %s, %s, %s);
    , parameters: ('2023-12-12', 0.92873571, 145.69689646, 83.36205681)
[2023-12-12T23:14:42.670+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/currency_exchange_dag.py", line 61, in load_data_task
    hook.run(sql, parameters=values)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 421, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "usd_exchange_rate_pkey"
DETAIL:  Key (dt)=(2023-12-12) already exists.

[2023-12-12T23:14:42.904+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_exchange_v02, task_id=load_to_postgres, execution_date=20231203T100000, start_date=20231212T231438, end_date=20231212T231442
[2023-12-12T23:14:43.242+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 411 for task load_to_postgres (duplicate key value violates unique constraint "usd_exchange_rate_pkey"
DETAIL:  Key (dt)=(2023-12-12) already exists.
; 22990)
[2023-12-12T23:14:44.954+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T23:14:58.113+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
