[2023-12-11T22:36:51.582+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag_v02.insert_into_postgres_table scheduled__2023-12-01T12:00:00+00:00 [queued]>
[2023-12-11T22:36:51.644+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag_v02.insert_into_postgres_table scheduled__2023-12-01T12:00:00+00:00 [queued]>
[2023-12-11T22:36:51.652+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-12-11T22:36:53.340+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_postgres_table> on 2023-12-01 12:00:00+00:00
[2023-12-11T22:36:54.819+0000] {standard_task_runner.py:57} INFO - Started process 10515 to run task
[2023-12-11T22:36:55.489+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag_v02', 'insert_into_postgres_table', 'scheduled__2023-12-01T12:00:00+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmp_ihvnlmd']
[2023-12-11T22:36:56.344+0000] {standard_task_runner.py:85} INFO - Job 280: Subtask insert_into_postgres_table
[2023-12-11T22:36:58.462+0000] {task_command.py:416} INFO - Running <TaskInstance: postgres_dag_v02.insert_into_postgres_table scheduled__2023-12-01T12:00:00+00:00 [running]> on host d5f251ea7e03
[2023-12-11T22:37:00.715+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sajal' AIRFLOW_CTX_DAG_ID='postgres_dag_v02' AIRFLOW_CTX_TASK_ID='insert_into_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T12:00:00+00:00'
[2023-12-11T22:37:01.267+0000] {sql.py:274} INFO - Executing: 
        insert into dag_runs(dt, dag_id) values ( '2023-12-01', 'postgres_dag_v02')
    
[2023-12-11T22:37:01.380+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-11T22:37:01.689+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-11T22:37:01.971+0000] {sql.py:418} INFO - Running statement: 
        insert into dag_runs(dt, dag_id) values ( '2023-12-01', 'postgres_dag_v02')
    , parameters: None
[2023-12-11T22:37:02.040+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-12-01, postgres_dag_v02) already exists.

[2023-12-11T22:37:02.372+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag_v02, task_id=insert_into_postgres_table, execution_date=20231201T120000, start_date=20231211T223651, end_date=20231211T223702
[2023-12-11T22:37:02.560+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 280 for task insert_into_postgres_table (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-12-01, postgres_dag_v02) already exists.
; 10515)
[2023-12-11T22:37:03.580+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-11T22:37:08.653+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
