[2023-12-11T22:22:53.430+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_postgres_table scheduled__2023-12-11T00:15:00+00:00 [queued]>
[2023-12-11T22:22:53.600+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_postgres_table scheduled__2023-12-11T00:15:00+00:00 [queued]>
[2023-12-11T22:22:53.637+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-12-11T22:22:53.743+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-12-11 00:15:00+00:00
[2023-12-11T22:22:54.804+0000] {standard_task_runner.py:57} INFO - Started process 4900 to run task
[2023-12-11T22:22:55.948+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_postgres_table', 'scheduled__2023-12-11T00:15:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmp1dcuwsji']
[2023-12-11T22:22:57.659+0000] {standard_task_runner.py:85} INFO - Job 121: Subtask create_postgres_table
[2023-12-11T22:23:02.948+0000] {task_command.py:416} INFO - Running <TaskInstance: postgres_dag.create_postgres_table scheduled__2023-12-11T00:15:00+00:00 [running]> on host d5f251ea7e03
[2023-12-11T22:23:06.034+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sajal' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T00:15:00+00:00'
[2023-12-11T22:23:06.289+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-12-11T22:23:06.544+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-11T22:23:07.668+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-11T22:23:07.831+0000] {sql.py:418} INFO - Running statement: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2023-12-11T22:23:08.196+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(dag_runs, 2200) already exists.

[2023-12-11T22:23:09.563+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_postgres_table, execution_date=20231211T001500, start_date=20231211T222253, end_date=20231211T222309
[2023-12-11T22:23:16.677+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 121 for task create_postgres_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(dag_runs, 2200) already exists.
; 4900)
[2023-12-11T22:23:44.317+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2023-12-11T22:23:44.700+0000] {process_utils.py:131} INFO - Sending 15 to group 4900. PIDs of all processes in the group: [4900]
[2023-12-11T22:23:44.731+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 4900
[2023-12-11T22:23:45.242+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4900, status='terminated', exitcode=1, started='22:22:54') (4900) terminated with exit code 1
