[2023-12-12T23:09:11.414+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_exchange.delete_from_postgres_table scheduled__2023-12-02T10:00:00+00:00 [queued]>
[2023-12-12T23:09:12.482+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_exchange.delete_from_postgres_table scheduled__2023-12-02T10:00:00+00:00 [queued]>
[2023-12-12T23:09:12.522+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-12-12T23:09:19.814+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): delete_from_postgres_table> on 2023-12-02 10:00:00+00:00
[2023-12-12T23:09:26.751+0000] {standard_task_runner.py:57} INFO - Started process 21535 to run task
[2023-12-12T23:09:28.270+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'currency_exchange', 'delete_from_postgres_table', 'scheduled__2023-12-02T10:00:00+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/currency_exchange_dag.py', '--cfg-path', '/tmp/tmp1j11hgo8']
[2023-12-12T23:09:29.134+0000] {standard_task_runner.py:85} INFO - Job 376: Subtask delete_from_postgres_table
[2023-12-12T23:09:36.854+0000] {task_command.py:416} INFO - Running <TaskInstance: currency_exchange.delete_from_postgres_table scheduled__2023-12-02T10:00:00+00:00 [running]> on host d5f251ea7e03
[2023-12-12T23:09:42.660+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'delete_from_postgres_table', field 'sql'. Template: '\n            delete from usd_exchange_rate where dt = \'{{ exchange_rates_data["date"] }}\';\n        '
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 303, in getitem
    return obj[argument]
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'exchange_rates_data' is undefined
[2023-12-12T23:09:42.868+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 303, in getitem
    return obj[argument]
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'exchange_rates_data' is undefined
[2023-12-12T23:09:43.152+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_exchange, task_id=delete_from_postgres_table, execution_date=20231202T100000, start_date=20231212T230911, end_date=20231212T230943
[2023-12-12T23:09:43.317+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 376 for task delete_from_postgres_table ('exchange_rates_data' is undefined; 21535)
[2023-12-12T23:09:43.777+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T23:09:45.090+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
