[2023-12-11T22:34:21.625+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.insert_into_postgres_table scheduled__2023-12-11T14:00:00+00:00 [queued]>
[2023-12-11T22:34:21.674+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.insert_into_postgres_table scheduled__2023-12-11T14:00:00+00:00 [queued]>
[2023-12-11T22:34:21.686+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-12-11T22:34:21.776+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_postgres_table> on 2023-12-11 14:00:00+00:00
[2023-12-11T22:34:21.823+0000] {standard_task_runner.py:57} INFO - Started process 9641 to run task
[2023-12-11T22:34:21.891+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'insert_into_postgres_table', 'scheduled__2023-12-11T14:00:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmpbby0p18s']
[2023-12-11T22:34:21.931+0000] {standard_task_runner.py:85} INFO - Job 242: Subtask insert_into_postgres_table
[2023-12-11T22:34:23.005+0000] {task_command.py:416} INFO - Running <TaskInstance: postgres_dag.insert_into_postgres_table scheduled__2023-12-11T14:00:00+00:00 [running]> on host d5f251ea7e03
[2023-12-11T22:34:23.902+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sajal' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='insert_into_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T14:00:00+00:00'
[2023-12-11T22:34:23.926+0000] {sql.py:274} INFO - Executing: 
        insert into dag_runs(dt, dag_id) values ( '2023-12-11', 'postgres_dag')
    
[2023-12-11T22:34:24.379+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-11T22:34:24.574+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-11T22:34:24.678+0000] {sql.py:418} INFO - Running statement: 
        insert into dag_runs(dt, dag_id) values ( '2023-12-11', 'postgres_dag')
    , parameters: None
[2023-12-11T22:34:24.692+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-12-11, postgres_dag) already exists.

[2023-12-11T22:34:24.770+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=insert_into_postgres_table, execution_date=20231211T140000, start_date=20231211T223421, end_date=20231211T223424
[2023-12-11T22:34:25.150+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 242 for task insert_into_postgres_table (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-12-11, postgres_dag) already exists.
; 9641)
[2023-12-11T22:34:25.431+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-11T22:34:26.107+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
